name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: query
        uses: romnn/query-git-action@main
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 21.x
          registry-url: https://registry.npmjs.org
          always-auth: true
      - run: bun install
      - run: bun run build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: query
        uses: romnn/query-git-action@main
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 21.x
          registry-url: https://registry.npmjs.org
          always-auth: true
      - uses: arduino/setup-protoc@v3
      - run: npm install -g @bufbuild/buf
      - run: bun install
      - run: ./test.sh
